# Generated by Django 5.1 on 2024-08-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='publish_tame',
            new_name='publish_time',
        ),
    ]
