# Generated by Django 5.1 on 2024-08-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districts',
            options={'ordering': ['order_id', 'id'], 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'ordering': ['order_id', 'id'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='socials',
            options={'verbose_name': 'Social', 'verbose_name_plural': 'Socials'},
        ),
    ]
