# Generated by Django 5.1 on 2024-09-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_districts_options_alter_regions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='common.regions'),
        ),
    ]
