# Generated by Django 5.1 on 2024-09-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contract_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
