# Generated by Django 5.1 on 2024-08-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_faculty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction', to='education.faculty'),
        ),
    ]
